# 开发环境配置(配置项只包括环境不同项)
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/seahouse?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    redis:
      # 服务器IP地址
      host: 127.0.0.1
      # 连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: