# 开发环境配置(配置项只包括环境不同项)
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/seahouse?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    redis:
      # 服务器IP地址
      host: 127.0.0.1
      # 连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:

    mail:
      host: "smtp.163.com"
      username: "vanguardd@163.com"
      password: "vanguard950124"

jwt:
  header: Authorization
  secret: "spring-security-@Jwt!&Secret^#"
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      refresh: "auth/refresh"
      register: "auth/register"
      password:
        login: "auth/login"
      mobilePhone:
        login: "auth/mobile/login"
      Oauth:
        login: "auth/Oauth/login"

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

sms:
  host: "http://localhost:8081/sendMsg"
  username: "vanguard"
  password: "vangaurd"
  apiKey: "key"
  expireTime: 600

REDIS_TRACKS_PRE: "TRACKS"
REDIS_SMS_PRE: "SMS"


