# 开发环境配置(配置项只包括环境不同项)
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.120:3306/seahouse?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: seahouse
      password: 1234
    redis:
      # 服务器IP地址
      host: 192.168.1.120
      # 连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:

    mail:
      host: "smtp.163.com"
      username: "vanguardd@163.com"
      password: "vanguard950124"

jwt:
  header: Authorization
  secret: "spring-security-@Jwt!&Secret^#"
  access_token:
    expiration: 86400
  refresh_token:
    expiration: 2592000
  tokenHead: "Bearer "
  route:
    authentication:
      refresh: "auth/refresh_token"
      register: "auth/register"
      password:
        login: "auth/login"
      mobilePhone:
        login: "auth/mobile/login"
      Oauth:
        login: "auth/Oauth/login"

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
    tk.mybatis: DEBUG

sms:
  host: "http://localhost:8081/sendMsg"
  username: "vanguard"
  password: "vangaurd"
  apiKey: "key"
  expireTime: 600

REDIS_TRACKS_PRE: "TRACKS"
REDIS_SMS_PRE: "SMS"

#七牛云
ACCESS_KEY: "5G2mrt4e3LrBZdjLeFgG7y5iB1A12hUplVKWKbS5"
SECRET_KEY: "7qAbiCfjxyk8OquqsEOIZXX8amNbUY0VdHnhqQov"
BUCKET: "seahouse"


